chore: update license headers in YAML files

diff --git a/.github/workflows/licence-check.yml b/.github/workflows/licence-check.yml
--- a/.github/workflows/licence-check.yml
+++ b/.github/workflows/licence-check.yml
@@ -51,15 +51,15 @@ jobs:
 
       - name: Check YAML licence headers
         run: |
-          header="# Copyright (C) 2025 Frachtwerk GmbH, Leopoldstraße 7C, 76133 Karlsruhe.\n#\n# This file is part of essencium-backend.\n#"
+          header="# Copyright (C) 2025 Frachtwerk GmbH, Leopoldstraße 7C, 76133 Karlsruhe."
           fail=0
           while IFS= read -r -d '' file; do
-            head=$(head -n 4 "$file" | tr -d '\r')
-            if [[ "$head" != "$header" ]]; then
-              echo "::error file=$file::Lizenz-Header fehlt oder ist falsch."
-              fail=1
-            fi
+          head=$(head -n 1 "$file" | tr -d '\r')
+          if [[ "$head" != "$header" ]]; then
+          echo "::error file=$file::Lizenz-Header fehlt oder ist falsch. ("$head" != "$header")"
+          fail=1
+          fi
           done < <(find . -type f \( -name "*.yml" -o -name "*.yaml" \) -print0)
           if [[ $fail -eq 1 ]]; then
-            exit 1
+          exit 1
           fi
